# -*- mode: Makefile -*-
#

$(call sm-check-not-empty, ds.ui.dir)
$(call sm-check-not-empty, ds.third.dir)
$(call sm-check-not-empty, ds.third.dir.inc)
$(call sm-check-not-empty, ds.third.dir.lib)
# $(call sm-check-not-empty, ds.third.dir.tmp)
$(call sm-check-not-empty, ds.third.libxml)
$(call sm-check-not-empty, ds.third.libpng)
#$(call sm-check-not-empty, ds.third.libiconv)
$(call sm-check-not-empty, ds.third.icu4c)
$(call sm-check-not-empty, ds.third.zlib)
# $(call sm-check-not-empty, ds.third.code.libxml)
# $(call sm-check-not-empty, ds.third.code.libpng)
# #$(call sm-check-not-empty, ds.third.code.libiconv)
# $(call sm-check-not-empty, ds.third.code.icu4c)
# $(call sm-check-not-empty, ds.third.code.zlib)
$(call sm-check-not-empty, ds.third.boost.dir)
$(call sm-check-not-empty, ds.third.boost.dir.lib)
$(call sm-check-not-empty, ds.third.boost.use)

$(call sm-check-exists, $(ds.third.dir))
$(call sm-check-exists, $(ds.third.dir.inc))
$(call sm-check-exists, $(ds.third.dir.lib))
# $(call sm-check-exists, $(ds.third.dir.tmp))
# $(call sm-check-exists, $(ds.third.dir.tmp)/$(ds.third.libxml)/include)
# $(call sm-check-exists, $(ds.third.dir.tmp)/$(ds.third.libxml)/include/libxml/xmlversion.h)
# $(call sm-check-exists, $(ds.third.dir)/$(ds.third.code.libxml)/include)
# $(call sm-check-exists, $(ds.third.dir)/$(ds.third.code.libpng))
# $(call sm-check-exists, $(ds.third.dir)/$(ds.third.code.libiconv))
# $(call sm-check-exists, $(ds.third.dir)/$(ds.third.code.zlib))
$(call sm-check-exists, $(ds.third.boost.dir))
$(call sm-check-exists, $(ds.third.boost.dir.lib))
